add trace process

diff --git a/badown b/badown
--- a/badown
+++ b/badown
@@ -1,6 +1,6 @@
 #!/bin/bash
 function log {
-   echo $1
+   echo -e $1 >> badown.debug
 }
 function url_str {
    echo $1\
@@ -80,8 +80,14 @@ function file_downdec {
    rm -f "$2".tmp
 }
 function file_down {
+   log 'starting download'
+   log "fetch uri: $1"
+   log "save to: $2.tmp"
    wget -O "$2".tmp $speed -q --show-progress "$1"
+   log 'download finished'
+   log "move file $2.tmp to $2"
    mv "$2".tmp "$2"
+   log 'successful download'
 }
 function tree_gen {
    local i=0
@@ -161,21 +167,45 @@ function zippyshare {
    file_down $file_url "$file_name"
 }
 function mediafire {
+   log 'get download uri original file'
    file_url=$(wget -q -O- $1 | grep  :\/\/download | awk -F'"' '{print $2}')
-   log $file_url
+   log "uri to download: '$file_url'"
+   log 'get filename form uri'
    file_name=$(printf '%b' "$(echo $file_url | awk -F'/' '{print $NF}')")
-   log $file_name
+   log "filename to save: $file_name"
    file_down $file_url "$file_name"
 }
 function uptobox {
-   rm -r *.cookie
-   rm -r *.rar
+   log 'clean temp files'
+   if test -f "get.cookie"; then
+      rm -r get.cookie
+   fi
+   if test -f "login.cookie"; then
+      rm -r login.cookie
+   fi
 
+   log 'sucess clean temp files'
    #start login
-   curl -c login.cookie https://uptobox.com/login > /dev/null
-   curl -c get.cookie --location --request POST https://uptobox.com/login --data-raw 'login=thexholo&password=*xSKSz4b%3B7%2FTk9s' --header 'referer: https://uptobox.com/login' > /dev/null
-   #end login
+   log 'login on uptobox with credentials'
+   log 'get cookie from login home'
 
+   curl -s -c login.cookie https://uptobox.com/login > /dev/null
+   log 'send credential and cookie to login action'
+   log "credentials \n\t user:'$UPTOBOX_USER'\n\t pwd: '$UPTOBOX_PWD'"
+   # curl -s -c get.cookie --location --request POST https://uptobox.com/login --data-raw 'login=thexholo&password=MJZdi6hQcwCWcy' --header 'referer: https://uptobox.com/login' > login.result
+   
+   login_result=$(curl -s -c get.cookie --location --request POST https://uptobox.com/login --data-raw "login=$UPTOBOX_USER&password=$UPTOBOX_PWD" --header 'referer: https://uptobox.com/login')
+   # log "login_result => $login_result"
+   is_success_login=$(echo "$login_result" | grep '<title>Home</title>')
+   log "is_success_login => $is_success_login"
+   if [[ "$is_success_login" == "" ]];then
+      log 'login error: invalid credentials'
+   else
+      log 'login success' 
+   fi
+
+   #end login   
+   log 'get download uri original file'
    gethtml=$(curl -s -b get.cookie $1)
    file_tag_token=$(echo "$gethtml" | grep 'waitingToken')
    log "TAG token=$file_tag_token"
@@ -184,9 +214,10 @@ function uptobox {
       log "no existe tag de token"
       #file allow for download
       file_url=$(curl -s --location --request POST  $1 | grep 'big-button-green-flat' | awk -F'"' '{print $2}')
-      log $file_url
+      log "uri to download: '$file_url'"
+      log 'get filename form uri'
       file_name=$(printf '%b' "$(echo $file_url | awk -F'/' '{print $NF}')")
-      log $file_name
+      log "filename to save: $file_name"
       file_down $file_url "$file_name"
    else
       log "existe tag de token"
@@ -196,25 +227,26 @@ function uptobox {
 
       if ! [[ "$file_token" == "" ]];then 
          #Lanzar POST con token
-         log "existe token"
+         log "existe value token"
          file_time_await=$(echo "$gethtml" | grep 'time-remaining' | awk -F"'"  '{print $4}')
-         log "AWAIT time=$file_time_await"
+         log "time await: '$file_time_await'"
          if ! [[ "$file_time_await" == "" ]];then
-            sleep 31
+            sleep $file_time_await
          fi         
-         file_response=$(curl -b get.cookie --location --request POST $1 --data-raw "waitingToken=$file_token")
+         file_response=$(curl -s -b get.cookie --location --request POST $1 --data-raw "waitingToken=$file_token")
          #echo $file_response
          file_url=$(echo "$file_response" | grep 'big-button-green-flat' | awk -F'"' '{print $2}')
          # | grep 'big-button-green-flat' | awk -F'"' '{print $2}')
-         log "url download=$file_url"
+         log "uri to download: '$file_url'"
+         log 'get filename form uri'
          file_name=$(printf '%b' "$(echo $file_url | awk -F'/' '{print $NF}')")
-         log $file_name
+         log "filename to save: $file_name"
          file_down $file_url "$file_name"
       else
-         log "no existe token"
+         log "no existe value token"
          file_time_await=$(echo "$gethtml" | grep 'time-remaining' | awk -F"'"  '{print $4}')
          
-         log "AWAIT time=$file_time_await"
+         log "time await: '$file_time_await'"
          while [[ "$file_token" == "" ]] || ! [[ "$file_time_await" == "0" ]]; do
             file_time_minutes=$(( file_time_await / 60 ))
             log "entro al while"
@@ -236,9 +268,10 @@ function uptobox {
          #echo $file_response
          file_url=$(echo "$file_response" | grep 'big-button-green-flat' | awk -F'"' '{print $2}')
          # | grep 'big-button-green-flat' | awk -F'"' '{print $2}')
-         log "url download=$file_url"
+         log "uri to download: '$file_url'"
+         log 'get filename form uri'
          file_name=$(printf '%b' "$(echo $file_url | awk -F'/' '{print $NF}')")
-         log $file_name
+         log "filename to save: $file_name"
          file_down $file_url "$file_name"
       fi
    fi
@@ -265,30 +298,53 @@ function 1fichier {
    file_down $file_url "$file_name"
 }
 function switch {
-   if [[ "$1" == *"mega"* ]];then
+   if test -f "$1"; then
+      log "request path: \t'$1'"
+      log "$1 exists."
+      for item in $(cat $1); do switch $item && sleep .5; done
+   elif [[ "$1" == *"mega"* ]];then
+      log "request uri: \t'$1' \nprovider: \t'mega'"
       mega "$1"
    elif [[ "$1" == *"zippyshare"* ]];then
+      log "request uri: \t'$1' \nprovider: \t'zippyshare'"
       zippyshare "$1"
    elif [[ "$1" == *"mediafire"* ]];then
+      log "request uri: \t'$1' \nprovider: \t'mediafire'"
       mediafire "$1"
    elif [[ "$1" == *"uptobox"* ]];then
+      log "request uri: \t'$1' \nprovider: \t'uptobox'"
       uptobox "$1"
    elif [[ "$1" == *"1fichier"* ]];then
+      log "request uri: \t'$1' \nprovider: \t'1fichier'"
       1fichier "$1"
    else
-      showhelp;exit 1
+      showhelp;
+      exit 1
    fi
 }
 function showhelp {
    echo -e "badown 0.4"
-   echo -e "bash downloader for hostsites like mega, uptobox, 1fichier, mediafire and zippyshare."
-   echo -e "badown [OPTION] ['URL']"
+   echo -e "bash downloader for hostsites"
+   echo -e "\t- mega"
+   echo -e "\t- uptobox"
+   echo -e "\t- 1fichier" 
+   echo -e "\t- mediafire" 
+   echo -e "\t- zippyshare"
+   echo -e "coming soon!!!"
+   echo -e "\t- google-drive (public files)"
+   echo -e "\t- fireload \n"
+   echo -e "badown [OPTION] ['URL' or 'FILE']"
    echo -e "\tOptions:"
    echo -e "\t-s,\t--speed SPEED         Download speed limit (integer values: 500B, 70K, 2M)."
-   echo -e "\t-h,\t--help             Display this help."
+   echo -e "\t-h,\t--help\t              Display this help."
    echo -e ""
    echo -e "if you find a bug, contact me @github -stck_lzm"
 }
+if [ -f .env ]
+then
+   export $(cat .env | sed 's/#.*//g' | xargs)
+fi
+
 TEMP=$(getopt -o "s:h"  --long "speed:,help" -n badown -- "$@")
 [ $? -eq 0 ] || {
 echo "Incorrect options provided"
