fix(:mediafire) get name from link

diff --git a/badown b/badown
--- a/badown
+++ b/badown
@@ -18,10 +18,10 @@ function json_post {
    echo $2\
       | awk -v c=$1 -F'"' '{for(i = 1; i <= NF; i++)
    {if($i==c)
-      if((c=="t")||(c=="s")||(c=="ts")) 
-	 {gsub(/[[:punct:]]/,"",$(i+1));print $(i+1);}
+      if((c=="t")||(c=="s")||(c=="ts"))
+         {gsub(/[[:punct:]]/,"",$(i+1));print $(i+1);}
       else
-	 {print $(i+2);}
+         {print $(i+2);}
       }
    }'
 }
@@ -71,11 +71,11 @@ function mega_link_vars {
    fi
 }
 function file_downdec {
-   wget -O "$2".tmp  $speed -q --show-progress "$1" 
+   wget -O "$2".tmp  $speed -q --show-progress "$1"
    cat "$2.tmp" \
       | openssl enc -d -aes-128-ctr -K $3 -iv $4 \
       > "$2"
-   rm -f "$2".tmp 
+   rm -f "$2".tmp
 }
 function file_down {
    wget -O "$2".tmp $speed -q --show-progress "$1"
@@ -94,8 +94,8 @@ function tree_gen {
    fi
 }
 function error {
-	echo -e "\033[31merror\e[0m: $1" 1>&2
-	exit 1
+        echo -e "\033[31merror\e[0m: $1" 1>&2
+        exit 1
 }
 function mega {
    mega_link_vars $1
@@ -108,40 +108,40 @@ function mega {
       attrs=($(json_post 'a' $response1 ))
       sizes=($(json_post 's' $response1 ))
       parents=($(json_post 'p' $response1 ))
-      for i in $(seq 0 $((${#types[@]}-1)));do 
-	 unset path
-	 tree_gen ${parents[i]} $((${#types[@]}-1))
-	 meta_dec_key "$(key_solver $(key_dec $(size ${keys[i]})))"
-	 file_name="$(json_post 'n' "$(meta_dec $meta_key $(size $(url_str ${attrs[i]})))")"
-	 path=$path/$file_name
-	 #echo -e "===\n${keys[i]}\n${names[i]}\n${types[i]}\n${attrs[i]}\n${sizes[i]}\n${parents[i]}\n"
-	 #hint if specific folder is specified in names and parents hold value
-	 #probably modify the init phase of mega function to carry new argument of specific folder to download
-	 #maybe add if condition to test how path relate to folder we want to download
-	 if [ -z $fid ]; then
-	    if [ ${types[i]} == 1 ];then
-	       sleep .5;mkdir -p "$PWD$path"
-	    elif [ ${types[i]} == 0 ];then
-	       file_url=$(json_post 'g' $(json_req "[{\"a\":\"g\",\"g\":1,\"n\":\"${names[i]}\"}]" "?id=&n=$id"))
-	       file_downdec $file_url "$file_name" $meta_key $meta_iv 
-	       sleep .5;mv "$file_name" "$PWD$path"
-	    fi
-	 else
-	    [ $fid == ${names[i]} ] &&\
-	       file_url=$(json_post 'g' $(json_req "[{\"a\":\"g\",\"g\":1,\"n\":\"${names[i]}\"}]" "?id=&n=$id")) &&\
-	       file_downdec $file_url "$file_name" $meta_key $meta_iv
-	 fi
+      for i in $(seq 0 $((${#types[@]}-1)));do
+         unset path
+         tree_gen ${parents[i]} $((${#types[@]}-1))
+         meta_dec_key "$(key_solver $(key_dec $(size ${keys[i]})))"
+         file_name="$(json_post 'n' "$(meta_dec $meta_key $(size $(url_str ${attrs[i]})))")"
+         path=$path/$file_name
+         #echo -e "===\n${keys[i]}\n${names[i]}\n${types[i]}\n${attrs[i]}\n${sizes[i]}\n${parents[i]}\n"
+         #hint if specific folder is specified in names and parents hold value
+         #probably modify the init phase of mega function to carry new argument of specific folder to download
+         #maybe add if condition to test how path relate to folder we want to download
+         if [ -z $fid ]; then
+            if [ ${types[i]} == 1 ];then
+               sleep .5;mkdir -p "$PWD$path"
+            elif [ ${types[i]} == 0 ];then
+               file_url=$(json_post 'g' $(json_req "[{\"a\":\"g\",\"g\":1,\"n\":\"${names[i]}\"}]" "?id=&n=$id"))
+               file_downdec $file_url "$file_name" $meta_key $meta_iv
+               sleep .5;mv "$file_name" "$PWD$path"
+            fi
+         else
+            [ $fid == ${names[i]} ] &&\
+               file_url=$(json_post 'g' $(json_req "[{\"a\":\"g\",\"g\":1,\"n\":\"${names[i]}\"}]" "?id=&n=$id")) &&\
+               file_downdec $file_url "$file_name" $meta_key $meta_iv
+         fi
       done
    elif [ "${fld: -1}" == "#" ] || [[ "$fld" == *"file"* ]];then
       meta_dec_key $(key_solver $(url_str $key))
       name_key=$(url_str $(json_post 'at' $(json_req "[{\"a\":\"g\", \"p\":\"$id\"}]" '?id=&ak=')))
       file_name="$(json_post 'n' "$(meta_dec $meta_key $(size $name_key))")"
       file_url=$(json_post 'g' $(json_req "[{\"a\":\"g\",\"g\":1,\"p\":\"$id\"}]" '?'))
-      file_downdec $file_url "$file_name" $meta_key $meta_iv 
+      file_downdec $file_url "$file_name" $meta_key $meta_iv
    fi
-   rm .badown.tmp
+   #rm .badown.tmp
 }
-function zippyshare { 
+function zippyshare {
    wget -q -O .badown.tmp $1
    var0=$(echo $1 \
       | awk -F".com" '{print $1".com"}')
@@ -159,11 +159,13 @@ function zippyshare {
    file_down $file_url "$file_name"
 }
 function mediafire {
-   file_url=$(wget -q -O- $1 \
-      | grep  :\/\/download \
-      | awk -F'"' '{print $2}')
-   file_name=$(printf '%b' "$(echo $file_url \
-      | awk -F'/' '{gsub("%","\\x");gsub("+"," ");print $NF}')")
+   file_url=$(wget -q -O- $1 | grep  :\/\/download | awk -F'"' '{print $2}')
+   echo $file_url
+
+   #file_name=$(printf '%b' "$(echo $file_url | awk -F'/' '{gsub("%","\\x");gsub("+"," ");print $NF}')")
+   file_name=$(printf '%b' "$(echo $file_url | awk -F'/' '{print $NF}')")
+   echo $file_name
+
    file_down $file_url "$file_name"
 }
 function switch {
@@ -183,7 +185,7 @@ function showhelp {
    echo -e "badown [OPTION] ['URL']"
    echo -e "\tOptions:"
    echo -e "\t-s,\t--speed SPEED         Download speed limit (integer values: 500B, 70K, 2M)."
-   echo -e "\t-h,\t--help  	      Display this help."
+   echo -e "\t-h,\t--help             Display this help."
    echo -e ""
    echo -e "if you find a bug, contact me @github -stck_lzm"
 }
@@ -195,10 +197,10 @@ exit 1
 eval set -- "$TEMP"
 while true; do
    case "$1" in
-      -s|--speed)		speed=" --limit-rate $2"; shift 2;;
-      -h|--help)		showhelp; exit 1;;
-      --)			shift; break;;
-      **)			showhelp;exit 1;;
+      -s|--speed)               speed=" --limit-rate $2"; shift 2;;
+      -h|--help)                showhelp; exit 1;;
+      --)                       shift; break;;
+      **)                       showhelp;exit 1;;
    esac
 done
 switch $1
